// This file will be generated by Supabase CLI
// For now, we'll define a basic structure that matches our schema

export interface Database {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string;
          name: string;
          ein: string;
          state: string;
          check_company_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          ein: string;
          state: string;
          check_company_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          ein?: string;
          state?: string;
          check_company_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      bank_accounts: {
        Row: {
          id: string;
          company_id: string;
          plaid_account_id: string;
          plaid_access_token: string;
          account_name: string;
          account_type: string;
          account_subtype: string | null;
          institution_name: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          plaid_account_id: string;
          plaid_access_token: string;
          account_name: string;
          account_type: string;
          account_subtype?: string | null;
          institution_name?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          plaid_account_id?: string;
          plaid_access_token?: string;
          account_name?: string;
          account_type?: string;
          account_subtype?: string | null;
          institution_name?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      payroll_runs: {
        Row: {
          id: string;
          company_id: string;
          check_payroll_id: string;
          pay_date: string;
          total_amount: number;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          check_payroll_id: string;
          pay_date: string;
          total_amount: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          check_payroll_id?: string;
          pay_date?: string;
          total_amount?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      balance_snapshots: {
        Row: {
          id: string;
          bank_account_id: string;
          balance: number;
          available_balance: number | null;
          snapshot_date: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          bank_account_id: string;
          balance: number;
          available_balance?: number | null;
          snapshot_date?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          bank_account_id?: string;
          balance?: number;
          available_balance?: number | null;
          snapshot_date?: string;
          created_at?: string;
        };
      };
      risk_assessments: {
        Row: {
          id: string;
          company_id: string;
          bank_account_id: string;
          payroll_run_id: string;
          current_balance: number;
          required_float: number;
          risk_status: 'safe' | 'at_risk' | 'critical';
          days_until_payroll: number;
          runway_days: number | null;
          assessed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          bank_account_id: string;
          payroll_run_id: string;
          current_balance: number;
          required_float: number;
          risk_status: 'safe' | 'at_risk' | 'critical';
          days_until_payroll: number;
          runway_days?: number | null;
          assessed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          bank_account_id?: string;
          payroll_run_id?: string;
          current_balance?: number;
          required_float?: number;
          risk_status?: 'safe' | 'at_risk' | 'critical';
          days_until_payroll?: number;
          runway_days?: number | null;
          assessed_at?: string;
          created_at?: string;
        };
      };
      alerts: {
        Row: {
          id: string;
          company_id: string;
          risk_assessment_id: string;
          alert_type: string;
          status: string;
          slack_message_ts: string | null;
          message_content: string | null;
          sent_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          risk_assessment_id: string;
          alert_type?: string;
          status?: string;
          slack_message_ts?: string | null;
          message_content?: string | null;
          sent_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          risk_assessment_id?: string;
          alert_type?: string;
          status?: string;
          slack_message_ts?: string | null;
          message_content?: string | null;
          sent_at?: string;
          created_at?: string;
      };
      employees: {
        Row: {
          id: string;
          company_id: string;
          name: string | null;
          title: string | null;
          salary: number | null;
          status: string | null;
          department: string | null;
          start_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          name?: string | null;
          title?: string | null;
          salary?: number | null;
          status?: string | null;
          department?: string | null;
          start_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string | null;
          title?: string | null;
          salary?: number | null;
          status?: string | null;
          department?: string | null;
          start_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      pay_schedules: {
        Row: {
          id: string;
          company_id: string;
          frequency: string | null;
          next_run_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          frequency?: string | null;
          next_run_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          frequency?: string | null;
          next_run_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}
