export const DEPARTMENTS = [
  'Engineering',
  'Product',
  'Design',
  'Marketing',
  'Sales',
  'Human Resources',
  'Operations',
  'Finance',
  'Legal',
  'Customer Support',
]

export const TITLES: string[] = [
  // Engineering
  'Software Engineer',
  'Senior Software Engineer',
  'Engineering Manager',
  'DevOps Engineer',
  'QA Engineer',
  'Data Engineer',
  // Product
  'Product Manager',
  'Senior Product Manager',
  'Product Owner',
  'Technical Product Manager',
  'Product Analyst',
  // Design
  'UX Designer',
  'UI Designer',
  'Product Designer',
  'Design Manager',
  'Graphic Designer',
  'UX Researcher',
  // Marketing
  'Marketing Coordinator',
  'Marketing Manager',
  'Content Strategist',
  'SEO Specialist',
  'Social Media Manager',
  'Growth Hacker',
  // Sales
  'Sales Representative',
  'Account Executive',
  'Sales Manager',
  'Business Development Rep',
  'Sales Operations',
  'Account Manager',
  // Human Resources
  'HR Coordinator',
  'HR Manager',
  'Recruiter',
  'Talent Acquisition Lead',
  'HR Generalist',
  'HR Business Partner',
  // Operations
  'Operations Coordinator',
  'Operations Manager',
  'Logistics Specialist',
  'Facilities Manager',
  'Project Coordinator',
  'Supply Chain Manager',
  // Finance
  'Financial Analyst',
  'Accountant',
  'Controller',
  'Finance Manager',
  'Bookkeeper',
  'Payroll Specialist',
  // Legal
  'Legal Counsel',
  'Paralegal',
  'Compliance Officer',
  'Contracts Manager',
  'Legal Assistant',
  'Chief Legal Officer',
  // Customer Support
  'Customer Support Rep',
  'Customer Success Manager',
  'Technical Support Engineer',
  'Support Team Lead',
  'Help Desk Specialist',
  'Customer Service Manager',
]
